networks:
  default:
    driver: bridge
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  zsocket_proxy:
    name: zsocket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
services:
  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder:telegraf
    tty: true
    container_name: ultrafeeder
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
      #devices:
      #- /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:80
      - 9273-9274:9273-9274
      - 30001-30006:30001-30006
      - 30104:30104
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ}
      # --------------------------------------------------
      # SDR related paramerters:
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_RTLSDR_DEVICE=1090
      - READSB_RTLSDR_PPM=-3
      #
      # --------------------------------------------------
      # READSB/Decoder parameters:
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_ALT=${FEEDER_ALT_M}m
      - READSB_GAIN=AUTOGAIN
        #- READSB_MODEAC=true
      - READSB_STATS_RANGE=true
      - READSB_FORWARD_MLAT_SBS=true
      #
      # --------------------------------------------------
      # Sources and aggregator connections:
      # (Note - remove the ones you are not using / feeding)
      - ULTRAFEEDER_CONFIG=
          adsb,dump978,30978,uat_in;
          adsb,feed.adsb.fi,30004,beast_reduce_plus_out;
          adsb,in.adsb.lol,30004,beast_reduce_plus_out;
          adsb,feed.airplanes.live,30004,beast_reduce_plus_out;
          adsb,feed.planespotters.net,30004,beast_reduce_plus_out;
          adsb,feed.theairtraffic.com,30004,beast_reduce_plus_out;
          adsb,skyfeed.hpradar.com,30004,beast_reduce_plus_out;
          adsb,feed.radarplane.com,30001,beast_reduce_plus_out;
          adsb,dati.flyitalyadsb.com,4905,beast_reduce_plus_out;
          adsb,data.avdelphi.com,24999,beast_reduce_plus_out;
          mlat,feed.adsb.fi,31090,39000;
          mlat,in.adsb.lol,31090,39001;
          mlat,feed.airplanes.live,31090,39002;
          mlat,mlat.planespotters.net,31090,39003;
          mlat,feed.theairtraffic.com,31090,39004;
          mlat,skyfeed.hpradar.com,31090,39005;
          mlat,feed.radarplane.com,31090,39006;
          mlat,dati.flyitalyadsb.com,30100,39007;
          mlathub,mlat.adamradloff.local,44441,beast_in;
          mlathub,mlat.adamradloff.local,44442,beast_in;
          mlathub,mlat.adamradloff.local,44443,beast_in
      # If you really want to feed ADSBExchange, you can do so  by adding this above: feed1.adsbexchange.com,30004,beast_reduce_plus_out
      - UUID=${MULTIFEEDER_UUID}
      - MLAT_USER=${FEEDER_NAME}
      #
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=true
      - TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
      - TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${FEEDER_NAME}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
   #"hosts": ["unix:///var/run/docker.sock", "tcp://<host IP address>:2376"]
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=2.0
      - TAR1090_RANGERINGSDISTANCES=50,100,150,200
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      - TAR1090_USEROUTEAPI=true
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_DARKMODE=true
      - ENABLE_978=yes
      - URL_978=http://dump978/skyaware978
      #
      # --------------------------------------------------
      # Prometheus and InfluxDB connection parameters:
      - INFLUXDBV2_URL=${INFLUX_URL}
      - INFLUXDBV2_TOKEN=${INFLUX_TOKEN}
      - INFLUXDBV2_ORG=ultrafeeder
      - INFLUXDBV2_BUCKET=${INFLUX_BUCKET}
      - PROMETHEUS_ENABLE=true
    volumes:
      #- $DOCKERDIR/appdata/adsb_readsbpb_rrd:/run/collectd
        #- $DOCKERDIR/appdata/adsb_readsbpb_autogain:/run/autogain
      - $DOCKERDIR/appdata/ultrafeeder/globe_history:/var/globe_history
      - $DOCKERDIR/appdata/ultrafeeder/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev:/dev:ro
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M

  dump978:
    image: ghcr.io/sdr-enthusiasts/docker-dump978:telegraf
    tty: true
    container_name: dump978
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 30978:30978
      - 30979:30979
      - 37981:37981
      - 30980:80
      - 9275:9273
    environment:
      - TZ=${FEEDER_TZ}
      - LAT=${FEEDER_LAT}
      - LON=${FEEDER_LONG}
      - DUMP978_RTLSDR_DEVICE=978
      - DUMP978_SDR_GAIN=autogain
      - AUTOGAIN_INITIAL_MSGS_ACCEPTED=3000
      - AUTOGAIN_FINETUNE_PERIOD=86400
      - AUTOGAIN_FINETUNE_MSGS_ACCEPTED=35000
      - AUTOGAIN_MIN_GAIN_VALUE=10
      - ENABLE_PROMETHEUS=true
    volumes:
      - $DOCKERDIR/appdata/adsb_dump978_autogain:/run/autogain
    tmpfs:
      - /run/readsb
      - /run/uat2json
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      zsocket_proxy:
        ipv4_address: 192.168.91.254 # You can specify a static IP
    privileged: true
    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer