services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
    - t2_proxy
    security_opt:
    - no-new-privileges:true
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=ultrafeeder
      - DOCKER_INFLUXDB_INIT_ORG=ultrafeeder
      #- DOCKER_INFLUXDB_INIT_RETENTION=1y
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    ports:
      - '8086:8086'
    volumes:
      - $DOCKERDIR/appdata/influx/influxdb_data:/var/lib/influxdb
      - $DOCKERDIR/appdata/influx/influxdb_config:/etc/influxdb
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.influx-rtr.entrypoints=websecure"
      - "traefik.http.routers.influx-rtr.rule=Host(`influx.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.influx-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.influx-rtr.service=influx-svc"
      - "traefik.http.services.influx-svc.loadbalancer.server.port=8086"